[optimal_lai_inputs]
git-tree-sha1 = "bd2ab975173bd27d03632bd2fbbae897696bf432"

    [[optimal_lai_inputs.download]]
    sha256 = "ae19213f1f17f4798a974aed88325b962299d534565da8e06b5e726bc3f3d39f"
    url = "https://caltech.box.com/shared/static/y8igrojuyvbww0gn5zi8und9wgsqhtv5.gz"
