[optimal_lai_inputs]
git-tree-sha1 = "cba8e02b52d8ebbde04a3fbb3269d775a6a08cc3"

    [[optimal_lai_inputs.download]]
    sha256 = "d23d59d049eaa49a53d6e4b53c310caa9409783d471de83c0ee97375c00228d4"
    url = "https://caltech.box.com/shared/static/y8igrojuyvbww0gn5zi8und9wgsqhtv5.gz"
