[era5_land_fraction]
git-tree-sha1 = "7f14ef1c7859da1363b8973743b2a376c008f29f"

    [[era5_land_fraction.download]]
    sha256 = "1d6acf98656b50f1a324ee3daa267281fb017314d2169dbfda25208299f44870"
    url = "https://caltech.box.com/shared/static/glqlyb626j3szcjltyuwp534yzzhf770.gz"
