[soil_ic_10m]
git-tree-sha1 = "b2384a4f494d37369caa0ea26bec4a7bbc9a6b8e"

    [[soil_ic_10m.download]]
    sha256 = "65e4599f8c8c8c0d6a0aedddb2d0e815ce291c6d746595c9191319a370cd6f23"
    url = "https://caltech.box.com/shared/static/vh9hht0jbl227w82vxhihsfkscx4iq0i.gz"
